task: vqgan

run_time:
  gpu_ids: [0]

model:
  type: vqgan
  disc_init_weights: false
  img_size: 256
  in_channels: 3
  latent_dim: 4
  num_embeddings: 8192
  commitment_cost: 0.2

dataset:
  name: custom
  root: ./data/celeba_hq_256
  in_channels: 3
  img_size: 256

train:
  epochs: 80
  batch_size: 16
  num_workers: 4
  learning_rate: 4.5e-06
  weight_decay: 0.0
  optimizer: adam
  beta1: 0.5
  beta2: 0.999
  perceptual_weight: 1.0
  codebook_weight: 1.0
  commitment_weight: 0.25
  disc_weight: 0.25
  disc_step_start: 15000