task: stable_diffusion

model:
  type: ddpm
  img_size: 32        
  in_channels: 4
  num_res_blocks: 2      
  dim: 64                 
  dim_mults: [1, 2, 4, 8]
  attn_layers: [8, 16]
  dropout: 0.0
  use_biggan_resample: false

dataset:
  name: custom
  root: ./data/celeba_hq_256
  in_channels: 3
  img_size: 256

first_stage:
  type: vqgan
  reg_type: vq
  img_size: 256
  latent_dim: 4
  checkpoint_path: ./output/vae/vqvae_vq_celebA_HQ_03030151/checkpoints/vqvae_autoencoder_final.pth

train:
  iterations: 300000      # ~300K iterations (DDPM needs long training)
  batch_size: 64         
  num_workers: 4
  learning_rate: 0.0002 
  loss_fn: mse
  optimizer: adam
  ema: true
  ema_decay: 0.9999

diffusion:
  diffuser: ddpm_scheduler 
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  variance_type: fixed_small
  use_cfg: false  # Unconditional generation