task: vae

run_time:
  gpu_ids: [1]
  
model:
  type: vqvae
  reg_type: kl
  disc_init_weights: false
  img_size: 256
  in_channels: 3
  latent_dim: 4

dataset:
  name: custom
  root: ./data/CelebA-HQ-img
  in_channels: 3
  img_size: 256

train:
  epochs: 80
  batch_size: 16
  num_workers: 4
  learning_rate: 4.5e-06
  weight_decay: 0.0
  optimizer: adam
  beta1: 0.5
  beta2: 0.999
  kl_beta: 1.0e-06
  perceptual_weight: 1.0
  disc_weight: 0.25
  disc_step_start: 15000