task: vae

model:
  type: vqvae
  reg_type: kl
  img_size: 256
  in_channels: 3
  latent_dim: 4

dataset:
  name: custom
  root: ./data/celeba_hq_256

train:
  epochs: 80
  batch_size: 8 
  num_workers: 4
  learning_rate: 0.0005
  weight_decay: 0.0
  optimizer: adam
  kl_beta: 0.1
  beta1: 0.5
  beta2: 0.999
  disc_step_start: 15000